import{a as E,S as q,i as p}from"./assets/vendor-DQvd0HNi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const s of n.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function l(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const M="55158990-7244be83249386c7e2b523135",P=E.create({baseURL:"https://pixabay.com/api/"});async function y(e,r){return(await P.get("",{params:{key:M,q:e,page:r,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const g=document.querySelector(".gallery"),m=document.querySelector(".loader"),b=document.querySelector(".load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function B({webformatURL:e,largeImageURL:r,tags:o,likes:l,views:t,comments:n,downloads:s}){return`<li class="gallery-item">
		<a class="gallery-link" href="${r}">
			<img class="gallery-image" src="${e}" alt="${o}" loading="lazy" />
		</a>
		<div class="image-info">
			<p><b>Likes</b><span>${l}</span></p>
			<p><b>Views</b><span>${t}</span></p>
			<p><b>Comments</b><span>${n}</span></p>
			<p><b>Downloads</b><span>${s}</span></p>
		</div>
	</li>`}function L(e){const r=e.map(B).join("");g.insertAdjacentHTML("beforeend",r),$.refresh()}function C(){g.innerHTML=""}function w(){m.classList.remove("is-hidden")}function S(){m.classList.add("is-hidden")}function d(){b.classList.remove("is-hidden")}function u(){b.classList.add("is-hidden")}const H=document.querySelector(".search-form"),O=document.querySelector(".load-more"),x=document.querySelector(".gallery");let f="",i=1,c=0,a=0;H.addEventListener("submit",I);O.addEventListener("click",R);async function I(e){e.preventDefault();const r=e.currentTarget.elements.searchQuery.value.trim();if(u(),C(),!r){D("Please enter a search query.");return}f=r,i=1,c=0,a=0,w();try{const o=await y(f,i);if(o.hits.length===0){h("Sorry, there are no images matching your search query. Please try again!");return}c=o.totalHits,a=o.hits.length,L(o.hits),a<c?d():(u(),v("We're sorry, but you've reached the end of search results."))}catch(o){h((o==null?void 0:o.message)||"Something went wrong. Please try again later.")}finally{S()}}async function R(){i+=1,u(),w();try{const e=await y(f,i);if(a+=e.hits.length,L(e.hits),A(),a>=c){u(),v("We're sorry, but you've reached the end of search results.");return}d()}catch(e){i-=1,h((e==null?void 0:e.message)||"Something went wrong. Please try again later."),a<c&&d()}finally{S()}}function A(){const e=x.firstElementChild;if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}function h(e){p.error({message:e,position:"topRight"})}function D(e){p.warning({message:e,position:"topRight"})}function v(e){p.info({message:e,position:"topRight"})}
//# sourceMappingURL=index.js.map
